service: app-appointment
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    TABLE_NAME: Appointment
    TOPIC_ARN:
      Ref: AppointmentTopic
  iam:
    role:
      statements:
        # Permisos para DynamoDB
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt AppointmentTable.Arn

        # Permisos para publicar en SNS
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - !Ref AppointmentTopic

        # Permisos para enviar mensajes a SQS
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - !GetAtt SqsPE.Arn
            - !GetAtt SqsCL.Arn
            - !GetAtt AppointmentResultQueue.Arn

        # Permisos para enviar eventos a EventBridge
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource:
            - arn:aws:events:${self:provider.region}:${aws:accountId}:event-bus/default

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    external:
      - aws-sdk

functions:
  # Lambda para agendar cita
  # Lambda para y vertificar el estado de cita
  Appointment:
    handler: src/infrastructure/lambdas/appointment/handler.appointment
    environment:
      APPPOINTMENT_TABLE: 
        Ref: AppointmentTable
    events:
      - httpApi:
          path: /appointment
          method: post
      - httpApi:
          path: /appointment/{insuredId}
          method: get
      - sqs:
          arn:
            Fn::GetAtt: [AppointmentResultQueue, Arn]

  # Lambda para listar citas
  listAppointments:
    handler: src/infrastructure/lambdas/appointment/handler.listAppointments
    environment:
      APPPOINTMENT_TABLE: 
        Ref: AppointmentTable
    events:
      - httpApi:
          path: /list-appointment
          method: get

  # Lambda guardar cita en MySQL Perú
  AppointmentPE:
    handler: src/infrastructure/lambdas/appointmentPe/handler.appointmentPE
    environment:
      DB_HOST: db-mysql-pe.col66wciwk0h.us-east-1.rds.amazonaws.com
      DB_USER: admin
      DB_PASSWORD: Admin123
      DB_NAME: appointments_pe
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SqsPE, Arn]

  # Lambda guardar cita en MySQL Chile
  AppointmentCL:
    handler: src/infrastructure/lambdas/appointmentCL/handler.appointmentCL
    environment:
      DB_HOST: db-mysql-cl.col66wciwk0h.us-east-1.rds.amazonaws.com
      DB_USER: admin
      DB_PASSWORD: Admin123
      DB_NAME: appointments_cl
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SqsCL, Arn]

resources:
  Resources:
    # DynamoDB Table para citas
    AppointmentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Appointment
        AttributeDefinitions:
          - AttributeName: insuredId
            AttributeType: S
        KeySchema:
          - AttributeName: insuredId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    # SNS Topic para citas
    AppointmentTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: AppointmentTopic

    # SQS Queues para Perú
    SqsPE:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: appointment_pe

    # SQS Queues para Chile
    SqsCL:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: appointment_cl

    # Suscripciones SNS a SQS Perú
    SnsSubscriptionPE:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref AppointmentTopic
        Protocol: sqs
        Endpoint: !GetAtt SqsPE.Arn
        FilterPolicy:
          countryISO:
            - "PE"

    # Suscripciones SNS a SQS Chile
    SnsSubscriptionCL:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref AppointmentTopic
        Protocol: sqs
        Endpoint: !GetAtt SqsCL.Arn
        FilterPolicy:
          countryISO:
            - "CL"

    # SQS Queue para resultados de procesamiento de citas
    AppointmentResultQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: appointment_result

    # Permiso para que EventBridge pueda enviar mensajes a la SQS de resultados
    AppointmentResultQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref AppointmentResultQueue
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: events.amazonaws.com
              Action: sqs:SendMessage
              Resource: !GetAtt AppointmentResultQueue.Arn

    # Regla de EventBridge para enrutar eventos a la SQS de resultados
    AppointmentEventRule:
      Type: AWS::Events::Rule
      Properties:
        Name: AppointmentEventRule
        EventPattern:
          source:
            - "appointment.processor"
        Targets:
          - Arn: !GetAtt AppointmentResultQueue.Arn
            Id: "SendToResultQueue"

